SET DATESTYLE TO 'DMY';

CREATE TABLE SIMPLICITI_2023_anonymise (
    IMMAT VARCHAR(50),
    DATE_LEVEE DATE,
    CODE_CIRCUIT INT,
    CODE_INSEE INT,
    NB_LEVEES INT
);

CREATE TABLE SIE_2023_anonymise (   
    CODE VARCHAR(50),
    DATE_COLLECTE DATE,
    DATE_HEURE_DEBUT TIMESTAMP,
    DATE_HEURE_FIN TIMESTAMP,   
    MISSION VARCHAR(255),
    IMMAT VARCHAR(255),
    LIBELLE_CIRCUIT VARCHAR(255),
    TEMPS_D_ACTIVITE INT,
    TEMPS_D_ARRET INT,
    TEMPS_DE_MOTEUR_OFF INT,
    TEMPS_DE_PAUSE INT,
    TEMPS_DE_MARCHE_ARRIERE INT,
    TEMPS_DE_SERVICE INT,
    KM_D_ACTIVITE FLOAT,
    KM_DE_HLP FLOAT,
    KM_DE_MARCHE_ARRIERE FLOAT,
    KM_DE_SERVICE FLOAT,
    SOURCE VARCHAR(255),
    CODE_CIRCUIT INT,
    SECTEUR_CIRCUIT VARCHAR(255),
    TOURNEE_CIRCUIT VARCHAR(255),
    JOURS_CIRCUIT VARCHAR(255),
    FLUX_CIRCUIT VARCHAR(255)
);

CREATE TABLE Referentiel_Transporteur (
    CODE_TRANSPORTEUR INT,
    MODALITE_COLLECTE VARCHAR(255),
    NATURE_COLLECTE VARCHAR(255),
    SECTEUR_COLLECTE VARCHAR(255)
);

CREATE TABLE Referentiel_Commune (
    CODE_INSEE INT,
    NOM_COMMUNE VARCHAR(255),
    POPULATION_TOTALE INT
);

CREATE TABLE Referentiel_Athanor_produit (
    PRD_CODE INT,
    PRD_LIBELLE VARCHAR(255),
    PRD_SOURCE VARCHAR(255)
);

CREATE TABLE Athanor_caracterisations (
    FIQ_ORDRE INT,
    FIQ_PES INT,
    FIQ_TRA_CODE INT,
    FIQ_DATE_DEPOT DATE,
    FIQ_DATE_TRI DATE,
    MATERIAUX VARCHAR(255),
    POIDS_VRAC FLOAT,
    POIDS_SAC INT,
    FAMILLE_MATERIAUX VARCHAR(255)
);

CREATE TABLE Athanor_2023 (
    PES_NUMERO INT,
    PES_DATE_ENTREE DATE,
    PES_HEURE_ENTREE VARCHAR(10),
    PES_DATE_SORTIE DATE,
    PES_HEURE_SORTIE TIME,
    PES_POIDS_BRUT INT,
    PES_POIDS_NET INT,
    PES_TRA_ID VARCHAR(50),
    PES_PRD_ID INT,
    PES_SOURCE VARCHAR(100)
);

COPY Athanor_2023 FROM '/data_brut/Athanor_2023.csv' DELIMITER ';' CSV HEADER;
COPY Athanor_caracterisations FROM '/data_brut/Athanor_caracterisations.csv' DELIMITER ';' CSV HEADER;
COPY SIE_2023_anonymise FROM '/data_brut/SIE_2023_anonymise.csv' DELIMITER ';' CSV HEADER;
COPY SIMPLICITI_2023_anonymise FROM '/data_brut/SIMPLICITI_2023_anonymise.csv' DELIMITER ';' CSV HEADER;
COPY Referentiel_Athanor_produit FROM '/data_brut/Referentiel_Athanor_produit.csv' DELIMITER ',' CSV HEADER;
COPY Referentiel_Commune FROM '/data_brut/Referentiel_Commune.csv' DELIMITER ',' CSV HEADER;
COPY Referentiel_Transporteur FROM '/data_brut/Referentiel_Transporteur.csv' DELIMITER ',' CSV HEADER;