version: '3.8'

services:
  postgres:
    image: postgres:13
    container_name: postgres
    environment:
      POSTGRES_USER: superset
      POSTGRES_PASSWORD: superset
      POSTGRES_DB: superset
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  superset:
    image: apache/superset:latest
    container_name: superset
    environment:
      SUPERSET_LOAD_EXAMPLES: "no"
      SUPERSET_WEBSERVER_PORT: 8088
      SUPERSET_ADMIN_USER: admin
      SUPERSET_ADMIN_PASSWORD: admin
      SUPERSET_DB_URI: postgresql+psycopg2://superset:superset@postgres:5432/superset
    ports:
      - "8088:8088"
    depends_on:
      - postgres
    volumes:
      - superset_home:/app/superset_home

volumes:
  pgdata:
  superset_home:
